### ISSUE TITLE
Bad UI

### ISSUE THREAD

**Issue by mnxoid** [mnxoid/rubylearn#1]
Needs adding Bootstrap or something similar

**Comment by dmylian** [comment]
Agree, m8. Sounds like great UI solution. Could you host it on gh-pages to r8 overall experience?

**Comment by dmylian** [comment]
I wanna particip8!

**Comment by mnxoid** [comment]
@danny-mylian , I cannot host a ruby app on gh-pages but fortunately I've got it deployed to Heroku. See  description
